backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
media_folder: "_site/assets/images/post-images"
public_folder: "/assets/images/post-images"
local_backend: true
publish_mode: editorial_workflow

collections:
  # Latest news collection
  - name: "latest-news"
    label: "Latest News"
    folder: "src/pages/articles/latest-news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Tags (Add `lnsNew` for the post to show on the home page.)",
          name: "tags",
          widget: "list",
          default: ["lnsAll"],
        }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Latest speeches and press releases collection
  - name: "latest-speeches-and-press-releases"
    label: "Latest Speeches and Press Releases"
    folder: "src/pages/articles/latest-speeches-and-press-releases"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Tags (Add `lsprNew` for the post to show on the home page.)",
          name: "tags",
          widget: "list",
          default: ["lsprAll"],
        }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Featured videos collection
  - name: "featured-videos"
    label: "Featured Videos"
    folder: "src/pages/articles/featured-videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Paste emded youtube link", name: "link", widget: "string" }
      - {
          label: "Tags (Add `fvNew` for the post to show on the home page.)",
          name: "tags",
          widget: "list",
          default: ["fvAll"],
        }

  # File collections of the file lists
  - label: "List files"
    name: "Lists"
    format: "json"
    extension: "json"
    files:
      # Slide images
      - label: "Slides"
        name: "slides"
        file: "src/_data/slides.json"
        fields:
          - name: slideImages
            label: Main slide images
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image Source", name: "imageSrc", widget: "string" }
              - { label: "Image Alt", name: "imageAlt", widget: "string" }

      # External links
      - label: "External Links"
        name: "externalLinks"
        file: "src/_data/externalLinks.json"
        fields:
          - name: ministriesContactInfo
            label: Ministries Contact Info
            widget: list
            fields:
              - { label: "Number", name: "number", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Address", name: "address", widget: "string" }
              - { label: "Telephone", name: "telephone", widget: "string" }
              - { label: "Website", name: "website", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }

  # File collections of the downloads
  - label: "Downloads"
    name: "Downloads"
    format: "markdown"
    extension: "markdown"
    files:
      # Slide images
      - label: "Acts"
        name: "acts"
        file: "src/_data/acts.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Layout",
              name: "layout",
              widget: "string",
              default:"regular-page.njk",
            }
          - { label: "Text body", name: "textBody", widget: "markdown" }
